meta:
  engine: 4.1.0

units:
  # main variables
  ## keycap width
  keycap_x: 16.5
  ## keycap height
  keycap_y: 16.5
  ## space between keycaps
  spacing_unlimited: 1
  ### spacing limitation
  spacing: max(0.5, spacing_unlimited)
  ## additional spacing around the plate (2 is recomended)
  plate_spacing_unlimited: 2
  ### plate spacing limitation
  plate_spacing: max(spacing, plate_spacing_unlimited)
  ## is inner thumbs keycap 1.5x
  is_thumbs_inner_1_5_uncalculated: 0
  ### is inner thumbs keycap calculation
  is_thumbs_inner_1_5: (is_thumbs_inner_1_5_uncalculated == 1)

  # default values
  ## keys in column
  keys_x: 6
  ## amount of columns
  keys_y: 3
  key_spread: keycap_x + spacing
  key_padding: keycap_y + spacing
  stagger_step: 2.381
  thumb_keys_splay_unlimited: 11.94
  # thumb_keys_splay_unlimited: 0
  ### angle limitation
  thumb_keys_splay: min(max(0.001, thumb_keys_splay_unlimited), 45)

  # MCU
  ## space between inner row and mcu
  mcu_spacing: 2spacing
  mcu_x: 17.78
  mcu_y: 33
  mcu_shift_x: keycap_x/2 + mcu_spacing + mcu_x/2
  mcu_shift_y: +keycap_y/2 - mcu_y/2 - stagger_step

  # single key plate
  key_plate_x: keycap_x + plate_spacing
  key_plate_y: keycap_x + plate_spacing

  # tile key plate
  tile_plate_x: (keys_x * keycap_x + (keys_x - 1) * spacing)/keys_x
  tile_plate_y: (keys_y * keycap_y + (keys_y - 1) * spacing)/keys_y
  tile_shift_x: (-keycap_x/2 + keys_x * keycap_x/2 + (keys_x - 1) * spacing/2)/keys_x
  tile_shift_y: (-keycap_y/2 + keys_y * keycap_y/2 + (keys_y - 1) * spacing/2)/keys_y

  # column plate
  column_plate_x: key_plate_x
  column_plate_y: keys_y * tile_plate_y + plate_spacing
  column_plate_shift_x: 0
  column_plate_shift_y: 0

  # outer bottom plate
  outer_bottom_size_x: keys_x * tile_plate_x + plate_spacing
  outer_bottom_size_y: column_plate_y
  outer_bottom_shift_x: keys_x * tile_shift_x
  outer_bottom_shift_y: keys_y * tile_shift_y

  # ref positions
  ref_position_circle_radius: 1

  _1_2_x: 4(keycap_x + spacing)
  _1_2_y: stagger_step

  _1_8_x: (keycap_x + spacing)
  _1_8_y: 2stagger_step

  _2_3_x: -1.5(keycap_x+spacing)
  _2_3_y: -(keycap_y + spacing)

  _3_4_x: (keycap_x + spacing)/2 + cos((90 - thumb_keys_splay) * pi/180) * spacing/2 + cos(-thumb_keys_splay * pi/180) * spacing/2 + cos(-thumb_keys_splay * pi/180) * keycap_x/2 + cos((90 - thumb_keys_splay) * pi/180) * keycap_y/2
  _3_4_y: -(keycap_y + spacing)/2 + sin((90 - thumb_keys_splay) * pi/180) * spacing/2 + sin(-thumb_keys_splay * pi/180) * spacing/2 + sin((90 - thumb_keys_splay) * pi/180) * keycap_y/2 + sin(-thumb_keys_splay * pi/180) * keycap_x/2

  _4_5_x: -cos((90 - thumb_keys_splay) * pi/180) * keycap_y/2 + cos(-thumb_keys_splay * pi/180) * keycap_x/2 + cos(-thumb_keys_splay * pi/180) * spacing/2 - cos((90 - thumb_keys_splay) * pi/180) * spacing/2 + cos((90 - 2thumb_keys_splay) * pi/180) * spacing/2 + cos(-2thumb_keys_splay * pi/180) * spacing/2 + cos(-2thumb_keys_splay * pi/180) * keycap_x/2 + cos((90 - 2thumb_keys_splay) * pi/180) * (keycap_y + is_thumbs_inner_1_5 * keycap_y/2)/2
  _4_5_y: -sin((90 - thumb_keys_splay) * pi/180) * keycap_y/2 + sin(-thumb_keys_splay * pi/180) * keycap_x/2 + sin(-thumb_keys_splay * pi/180) * spacing/2 - sin((90 - thumb_keys_splay) * pi/180) * spacing/2 + sin((90 - 2thumb_keys_splay) * pi/180) * spacing/2 + sin(-2thumb_keys_splay * pi/180) * spacing/2 + sin((90 - 2thumb_keys_splay) * pi/180) *(keycap_y + is_thumbs_inner_1_5 * keycap_y/2)/2 + sin(-2thumb_keys_splay * pi/180) * keycap_x/2

  _2_6_x: 0
  _2_6_y: 2(keycap_y + spacing)

  _6_7_x: mcu_shift_x
  _6_7_y: mcu_shift_y

  _1_center_x: 0
  _1_center_y: 0

  _2_center_x: _1_center_x + _1_2_x
  _2_center_y: _1_center_y + _1_2_y

  _3_center_x: _2_center_x + _2_3_x
  _3_center_y: _2_center_y + _2_3_y

  _4_center_x: _3_center_x + _3_4_x
  _4_center_y: _3_center_y + _3_4_y

  _5_center_x: _4_center_x + _4_5_x
  _5_center_y: _4_center_y + _4_5_y

  _6_center_x: _2_center_x + _2_6_x
  _6_center_y: _2_center_y + _2_6_y

  _7_center_x: _6_center_x + _6_7_x
  _7_center_y: _6_center_y + _6_7_y

  _8_center_x: _1_center_x + _1_8_x
  _8_center_y: _1_center_y + _1_8_y

  _2_br_x: (keycap_x + mcu_spacing)/2
  _2_br_y: -(keycap_y + plate_spacing)/2

  _1_2_br_x: _2_center_x + _2_br_x
  _1_2_br_y: _2_center_y + _2_br_y

  _3_bl_x: -(keycap_x + plate_spacing)/2
  _3_bl_y: -(keycap_y + plate_spacing)/2

  _1_3_bl_x: _3_center_x + _3_bl_x
  _1_3_bl_y: _3_center_y + _3_bl_y

  _4_br_x: cos(-thumb_keys_splay * pi/180) * keycap_x/2 - cos((90 - thumb_keys_splay) * pi/180) * keycap_y/2 + cos(-thumb_keys_splay * pi/180) * plate_spacing/2 - cos((90 - thumb_keys_splay) * pi/180) * plate_spacing/2
  _4_br_y: sin(-thumb_keys_splay * pi/180) * keycap_x/2 - sin((90 - thumb_keys_splay) * pi/180) * keycap_y/2 + sin(-thumb_keys_splay * pi/180) * plate_spacing/2 - sin((90 - thumb_keys_splay) * pi/180) * plate_spacing/2

  _1_4_br_x: _4_center_x + _4_br_x
  _1_4_br_y: _4_center_y + _4_br_y

  _5_br_x: cos(-2thumb_keys_splay * pi/180) * keycap_x/2 - cos((90 - 2thumb_keys_splay) * pi/180) * keycap_y/2 + cos(-2thumb_keys_splay * pi/180) * plate_spacing/2 - cos((90 - 2thumb_keys_splay) * pi/180) * plate_spacing/2 - is_thumbs_inner_1_5 * cos((90 - 2thumb_keys_splay) * pi/180) * keycap_y/4
  _5_br_y: sin(-2thumb_keys_splay * pi/180) * keycap_x/2 - sin((90 - 2thumb_keys_splay) * pi/180) * keycap_y/2 + sin(-2thumb_keys_splay * pi/180) * plate_spacing/2 - sin((90 - 2thumb_keys_splay) * pi/180) * plate_spacing/2 - is_thumbs_inner_1_5 * sin((90 - 2thumb_keys_splay) * pi/180) * keycap_y/4
  _5_bl_x: -cos(-2thumb_keys_splay * pi/180) * keycap_x/2 - cos((90 - 2thumb_keys_splay) * pi/180) * keycap_y/2 - cos(-2thumb_keys_splay * pi/180) * plate_spacing/2 - cos((90 - 2thumb_keys_splay) * pi/180) * plate_spacing/2 - is_thumbs_inner_1_5 * cos((90 - 2thumb_keys_splay) * pi/180) * keycap_y/4
  _5_bl_y: -sin(-2thumb_keys_splay * pi/180) * keycap_x/2 - sin((90 - 2thumb_keys_splay) * pi/180) * keycap_y/2 - sin(-2thumb_keys_splay * pi/180) * plate_spacing/2 - sin((90 - 2thumb_keys_splay) * pi/180) * plate_spacing/2 - is_thumbs_inner_1_5 * sin((90 - 2thumb_keys_splay) * pi/180) * keycap_y/4
  _5_tr_x: cos(-2thumb_keys_splay * pi/180) * keycap_x/2 + cos((90 - 2thumb_keys_splay) * pi/180) * keycap_y/2 + cos(-2thumb_keys_splay * pi/180) * plate_spacing/2 + cos((90 - 2thumb_keys_splay) * pi/180) * plate_spacing/2 + is_thumbs_inner_1_5 * cos((90 - 2thumb_keys_splay) * pi/180) * keycap_y/4
  _5_tr_y: sin(-2thumb_keys_splay * pi/180) * keycap_x/2 + sin((90 - 2thumb_keys_splay) * pi/180) * keycap_y/2 + sin(-2thumb_keys_splay * pi/180) * plate_spacing/2 + sin((90 - 2thumb_keys_splay) * pi/180) * plate_spacing/2 + is_thumbs_inner_1_5 * sin((90 - 2thumb_keys_splay) * pi/180) * keycap_y/4
  _5_tl_x: -cos(-2thumb_keys_splay * pi/180) * keycap_x/2 + cos((90 - 2thumb_keys_splay) * pi/180) * keycap_y/2 - cos(-2thumb_keys_splay * pi/180) * plate_spacing/2 + cos((90 - 2thumb_keys_splay) * pi/180) * plate_spacing/2 + is_thumbs_inner_1_5 * cos((90 - 2thumb_keys_splay) * pi/180) * keycap_y/4
  _5_tl_y: -sin(-2thumb_keys_splay * pi/180) * keycap_x/2 + sin((90 - 2thumb_keys_splay) * pi/180) * keycap_y/2 - sin(-2thumb_keys_splay * pi/180) * plate_spacing/2 + sin((90 - 2thumb_keys_splay) * pi/180) * plate_spacing/2 + is_thumbs_inner_1_5 * sin((90 - 2thumb_keys_splay) * pi/180) * keycap_y/4

  _1_5_br_x: _5_center_x + _5_br_x
  _1_5_br_y: _5_center_y + _5_br_y
  _1_5_bl_x: _5_center_x + _5_bl_x
  _1_5_bl_y: _5_center_y + _5_bl_y
  _1_5_tr_x: _5_center_x + _5_tr_x
  _1_5_tr_y: _5_center_y + _5_tr_y
  _1_5_tl_x: _5_center_x + _5_tl_x
  _1_5_tl_y: _5_center_y + _5_tl_y

  _7_br_x: (mcu_x + plate_spacing)/2
  _7_br_y: -(mcu_y + plate_spacing)/2
  _7_tr_x: _7_br_x
  _7_tr_y: (mcu_y + plate_spacing)/2
  _7_tl_x: -(mcu_x + mcu_spacing)/2
  _7_tl_y: _7_tr_y

  _1_7_br_x: _7_center_x + _7_br_x
  _1_7_br_y: _7_center_y + _7_br_y
  _1_7_tr_x: _7_center_x + _7_tr_x
  _1_7_tr_y: _7_center_y + _7_tr_y
  _1_7_tl_x: _7_center_x + _7_tl_x
  _1_7_tl_y: _7_center_y + _7_tl_y

  _8_br_x: (keycap_x + spacing)/2
  _8_br_y: -(keycap_y + plate_spacing)/2 - 2stagger_step

  _1_8_br_x: _8_center_x + _8_br_x
  _1_8_br_y: _8_center_y + _8_br_y

  _s1_b_x: _1_7_br_x
  _s1_b_y: _1_5_tr_y
  _s1_t_x: _s1_b_x
  _s1_t_y: _1_7_br_y

  _2_6__5_intersection_x: ((_1_7_tl_x * _1_2_br_y - _1_7_tl_y * _1_2_br_x) * (_1_5_tl_x - _1_5_tr_x) - (_1_7_tl_x - _1_2_br_x) * (_1_5_tl_x * _1_5_tr_y - _1_5_tl_y * _1_5_tr_x)) / ((_1_7_tl_x - _1_2_br_x) * (_1_5_tl_y - _1_5_tr_y) - (_1_7_tl_y - _1_2_br_y) * (_1_5_tl_x - _1_5_tr_x))
  _2_6__5_intersection_y: ((_1_7_tl_x * _1_2_br_y - _1_7_tl_y * _1_2_br_x) * (_1_5_tl_y - _1_5_tr_y) - (_1_7_tl_y - _1_2_br_y) * (_1_5_tl_x * _1_5_tr_y - _1_5_tl_y * _1_5_tr_x)) / ((_1_7_tl_x - _1_2_br_x) * (_1_5_tl_y - _1_5_tr_y) - (_1_7_tl_y - _1_2_br_y) * (_1_5_tl_x - _1_5_tr_x))

  _3_4__5_intersection_x: ((_1_3_bl_x * _1_4_br_y - _1_3_bl_y * _1_4_br_x) * (_1_5_bl_x - _1_5_br_x) - (_1_3_bl_x - _1_4_br_x) * (_1_5_bl_x * _1_5_br_y - _1_5_bl_y * _1_5_br_x)) / ((_1_3_bl_x - _1_4_br_x) * (_1_5_bl_y - _1_5_br_y) - (_1_3_bl_y - _1_4_br_y) * (_1_5_bl_x - _1_5_br_x))
  _3_4__5_intersection_y: ((_1_3_bl_x * _1_4_br_y - _1_3_bl_y * _1_4_br_x) * (_1_5_bl_y - _1_5_br_y) - (_1_3_bl_y - _1_4_br_y) * (_1_5_bl_x * _1_5_br_y - _1_5_bl_y * _1_5_br_x)) / ((_1_3_bl_x - _1_4_br_x) * (_1_5_bl_y - _1_5_br_y) - (_1_3_bl_y - _1_4_br_y) * (_1_5_bl_x - _1_5_br_x))

  _5__7_intersection_numerator_x: ((_1_5_br_x - _1_5_tr_x) * (_1_7_tr_x * _1_7_br_y - _1_7_br_x * _1_7_tr_y) - (_1_7_br_x - _1_7_tr_x) * (_1_5_tr_x * _1_5_br_y - _1_5_br_x * _1_5_tr_y)) 
  _5__7_intersection_numerator_y: ((_1_5_br_y - _1_5_tr_y) * (_1_7_tr_x * _1_7_br_y - _1_7_br_x * _1_7_tr_y) - (_1_7_br_y - _1_7_tr_y) * (_1_5_tr_x * _1_5_br_y - _1_5_br_x * _1_5_tr_y))
  _5__7_intersection_denominator_x: ((_1_5_br_x - _1_5_tr_x) * (_1_7_br_y - _1_7_tr_y) - (_1_7_br_x - _1_7_tr_x) * (_1_5_br_y - _1_5_tr_y))
  _5__7_intersection_denominator_y: ((_1_5_br_x - _1_5_tr_x) * (_1_7_br_y - _1_7_tr_y) - (_1_7_br_x - _1_7_tr_x) * (_1_5_br_y - _1_5_tr_y))

  _5__7__no_s1_intersection_x: _5__7_intersection_numerator_x / _5__7_intersection_denominator_x
  _5__7__no_s1_intersection_y: _5__7_intersection_numerator_y / _5__7_intersection_denominator_y

  _5__7_intersection_x: _5__7__no_s1_intersection_x * (_s1_b_x == _5__7__no_s1_intersection_x == _s1_t_x) + _s1_b_x * (1 - (_s1_b_x == _5__7__no_s1_intersection_x == _s1_t_x))
  _5__7_intersection_y: _5__7__no_s1_intersection_y * (_s1_b_y <= _5__7__no_s1_intersection_y <= _s1_t_y) + _1_2_br_y * (1 - (_s1_b_y <= _5__7__no_s1_intersection_y <= _s1_t_y))

points:
  zones:
    matrix:
      key:
        padding: key_padding
        spread: key_spread
      columns:
        outer:
        pinky:
        ring:
          key.stagger: 2stagger_step
        middle:
          key.stagger: stagger_step
        index:
          key.stagger: -stagger_step
        inner:
          key.stagger: -stagger_step
      rows:
        bottom:
        home:
        top:
    thumbs:
      key:
        padding: key_padding
        spread: key_spread
      anchor:
        ref: matrix_inner_bottom
        shift: [-1.5(keycap_x + spacing), -(keycap_y + spacing)]
      columns:
        outer:
        middle:
          key:
            splay: -thumb_keys_splay
            origin: [-(keycap_x + spacing)/2, -(keycap_y + spacing)/2]
        inner:
          key:
            splay: -thumb_keys_splay
            origin: [-(keycap_x + spacing)/2, -(keycap_y + spacing)/2]
            shift: [0, is_thumbs_inner_1_5 * keycap_y/4]
            rotate: is_thumbs_inner_1_5 * 90
      rows:
        cluster:

outlines:
  keys:
    - what: rectangle
      where: true
      size: [keycap_x, keycap_y]
    - what: rectangle
      where:
        ref: thumbs_inner_cluster
      size: [keycap_x + is_thumbs_inner_1_5 * keycap_y/2, keycap_y]

  switches:
    - what: rectangle
      where: true
      size: [15, 15]

  mcu:
    - what: rectangle
      where:
        ref: matrix_inner_top
        shift: [mcu_shift_x, mcu_shift_y]
      size: [mcu_x, mcu_y]

  switches_and_mcu:
    - what: outline
      name: switches
    - what: outline
      name: mcu

  keys_and_mcu:
    - what: outline
      name: keys
    - what: outline
      name: mcu

  ref_pos:
    - what: outline
      name: keys
    - what: outline
      name: mcu
    # ref centers
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_1_center_x, _1_center_y]
      radius: ref_position_circle_radius
      operation: stack
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_2_center_x, _2_center_y]
      radius: ref_position_circle_radius
      operation: stack
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_3_center_x, _3_center_y]
      radius: ref_position_circle_radius
      operation: stack
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_4_center_x, _4_center_y]
      radius: ref_position_circle_radius
      operation: stack
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_5_center_x, _5_center_y]
      radius: ref_position_circle_radius
      operation: stack
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_6_center_x, _6_center_y]
      radius: ref_position_circle_radius
      operation: stack
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_7_center_x, _7_center_y]
      radius: ref_position_circle_radius
      operation: stack
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_8_center_x, _8_center_y]
      radius: ref_position_circle_radius
      operation: stack
    # inner matrix corners
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_1_2_br_x, _1_2_br_y]
      radius: ref_position_circle_radius
      operation: stack
    # outer thumb corners
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_1_3_bl_x, _1_3_bl_y]
      radius: ref_position_circle_radius
      operation: stack
    # middle thumb corners
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_1_4_br_x, _1_4_br_y]
      radius: ref_position_circle_radius
      operation: stack
    # inner thumb corners
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_1_5_br_x, _1_5_br_y]
      radius: ref_position_circle_radius
      operation: stack
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_1_5_bl_x, _1_5_bl_y]
      radius: ref_position_circle_radius
      operation: stack
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_1_5_tr_x, _1_5_tr_y]
      radius: ref_position_circle_radius
      operation: stack
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_1_5_tl_x, _1_5_tl_y]
      radius: ref_position_circle_radius
      operation: stack
    # mcu corners
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_1_7_br_x, _1_7_br_y]
      radius: ref_position_circle_radius
      operation: stack
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_1_7_tr_x, _1_7_tr_y]
      radius: ref_position_circle_radius
      operation: stack
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_1_7_tl_x, _1_7_tl_y]
      radius: ref_position_circle_radius
      operation: stack
    # bottom ring corners
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_1_8_br_x, _1_8_br_y]
      radius: ref_position_circle_radius
      operation: stack
    # intersections
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_2_6__5_intersection_x, _2_6__5_intersection_y]
      radius: ref_position_circle_radius
      operation: stack
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_3_4__5_intersection_x, _3_4__5_intersection_y]
      radius: ref_position_circle_radius
      operation: stack
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [_5__7_intersection_x, _5__7_intersection_y]
      radius: ref_position_circle_radius
      operation: stack

  mcu_plate:
    # mcu plate
    - what: polygon
      points:
        - ref: matrix_pinky_bottom
          shift: [_1_7_tl_x, _1_7_tl_y]
        - ref: matrix_pinky_bottom
          shift: [_1_7_tr_x, _1_7_tr_y]
        - ref: matrix_pinky_bottom
          shift: [_5__7_intersection_x, _5__7_intersection_y]
        - ref: matrix_pinky_bottom
          shift: [_1_5_tr_x, _1_5_tr_y]
        - ref: matrix_pinky_bottom
          shift: [_2_6__5_intersection_x, _2_6__5_intersection_y]

  matrix_plate:
    # outer bottom plate
    - what: rectangle
      where:
        ref: matrix_outer_bottom
        shift: [outer_bottom_shift_x, outer_bottom_shift_y]
      size: [outer_bottom_size_x, outer_bottom_size_y]
    # ring plate
    - what: rectangle
      where:
        ref: matrix_ring_home
        shift: [column_plate_shift_x, column_plate_shift_y]
      size: [column_plate_x, column_plate_y]
    # right ring plate
    - what: rectangle
      where:
        ref: matrix_ring_home
        shift: [column_plate_shift_x + (key_spread)/2, column_plate_shift_y]
      size: [column_plate_x, column_plate_y]
    # middle plate
    - what: rectangle
      where:
        ref: matrix_middle_home
        shift: [column_plate_shift_x, column_plate_shift_y]
      size: [column_plate_x, column_plate_y]
    # index plate
    - what: rectangle
      where:
        ref: matrix_index_home
        shift: [column_plate_shift_x, column_plate_shift_y]
      size: [column_plate_x, column_plate_y]
    # left index plate
    - what: rectangle
      where:
        ref: matrix_index_home
        shift: [column_plate_shift_x - (key_spread)/2, column_plate_shift_y]
      size: [column_plate_x, column_plate_y]
    # inner plate
    - what: rectangle
      where:
        ref: matrix_inner_home
        shift: [column_plate_shift_x, column_plate_shift_y]
      size: [column_plate_x, column_plate_y]
    # left inner plate
    - what: rectangle
      where:
        ref: matrix_inner_home
        shift: [column_plate_shift_x - (key_spread)/2, column_plate_shift_y]
      size: [column_plate_x, column_plate_y]

  thumbs_plate:
    - what: polygon
      points:
        - ref: matrix_pinky_bottom
          shift: [_1_8_br_x, _1_8_br_y]
        - ref: matrix_pinky_bottom
          shift: [_1_3_bl_x, _1_3_bl_y]
        - ref: matrix_pinky_bottom
          shift: [_3_4__5_intersection_x, _3_4__5_intersection_y]
        - ref: matrix_pinky_bottom
          shift: [_1_5_br_x, _1_5_br_y]
        - ref: matrix_pinky_bottom
          shift: [_1_5_tr_x, _1_5_tr_y]
        - ref: matrix_pinky_bottom
          shift: [_2_6__5_intersection_x, _2_6__5_intersection_y]
        - ref: matrix_pinky_bottom
          shift: [_1_2_br_x, _1_2_br_y]

  plate:
    # keys plate
    - what: rectangle
      where: true
      size: [key_plate_x, key_plate_y]
    # mcu
    - what: outline
      name: mcu
    # mcu plate
    - what: outline
      name: mcu_plate
    # matrix plate
    - what: outline
      name: matrix_plate
    # thumbs plate
    - what: outline
      name: thumbs_plate

pcbs:
  main:
    template: kicad8
    outlines:
      main:
        outline: plate
    footprints:
      keyswitches:
        where: true
        what: ceoloide/switch_choc_v1_v2
        params:
          hotswap: true
          reversible: true
          from: "{{col_net}}"
          to: "{{colrow}}"
      mcu:
        what: ceoloide/mcu_supermini_nrf52840
        params:
          reversible: true
        where:
          ref: matrix_inner_top
          shift: [mcu_shift_x, mcu_shift_y]
  ref_pos:
    template: kicad8
    outlines:
      main:
        outline: ref_pos
